# detection-rules config file
bbr_rules_dirs:
  - ../../rules_building_block
rule_dirs:
  - ../../rules
files:
  deprecated_rules: deprecated_rules.json
  packages: packages.yaml
  stack_schema_map: stack-schema-map.yaml
  version_lock: version.lock.json
normalize_kql_keywords: False
bypass_version_lock: False

# directories:
  # action_dir: actions
  # exception_dir: exceptions
  # action_connector_dir: action_connectors

# Custom rules directory setup
# If using custom rules, copy this file to the root of the custom rules directory and set paths accordingly.
# Use CUSTOM_RULES_DIR environment variable to point to your custom rules directory.

# Testing Configuration
# This points to the testing config file, which defines the tests to be run or bypassed.
testing:
  config: etc/example_test_config.yaml  # Use relative path to the test config file

# To turn on automatic schema generation for non-ecs fields via custom schemas use a line like the following.
# auto_gen_schema_file: "etc/auto-gen-schema.json"

# To bulk disable elastic validation for optional fields, use this:
# bypass_optional_elastic_validation: True
