[metadata]
creation_date = "2024/11/18"
maturity = "production"
updated_date = "2024/11/18"

[rule]
anomaly_threshold = 50
author = ["Elastic"]
description = """
A machine learning job detected a rare and unusual user agent indicating web browsing activity by an unusual process
other than a web browser. This can be due to persistence, command-and-control, or exfiltration activity. Uncommon user
agents coming from remote sources to local destinations are often the result of scanners, bots, and web scrapers, which
are part of common Internet background traffic. Much of this is noise, but more targeted attacks on websites using tools
like Burp or SQLmap can sometimes be discovered by spotting uncommon user agents. Uncommon user agents in traffic from
local sources to remote destinations can be any number of things, including harmless programs like weather monitoring or
stock-trading programs. However, uncommon user agents from local sources can also be due to malware or scanning
activity.
"""
enabled = true
exceptions_list = []
false_positives = [
    """
    Web activity that is uncommon, like security scans, may trigger this alert and may need to be excluded. A new or
    rarely used program that calls web services may trigger this alert.
    """,
]
from = "now-2700s"
interval = "15m"
license = "Elastic License v2"
machine_learning_job_id = ["orange-v1-packetbeat_rare_user_agent"]
max_signals = 100
name = "Orange-ML307 Unusual Web User Agent"
references = ["https://www.elastic.co/guide/en/security/current/prebuilt-ml-jobs.html"]
related_integrations = []
required_fields = []
revision = 0
risk_score = 21
risk_score_mapping = []
rule_id = "2fd1de6f-e2bb-4b6d-8a79-8808271159b5"
setup = ""
severity = "low"
severity_mapping = []
tags = ["Elastic", "Network", "Threat Detection", "ML", "Machine Learning", "Command and Control"]
to = "now"
type = "machine_learning"
version = 102
[[rule.actions]]
action_type_id = ".webhook"
group = "default"
id = "774395b0-e98a-11ed-a13a-3121123ca4d1"
uuid = "2c483f28-dea7-4bf2-99d5-47969658ed03"

[rule.actions.frequency]
notifyWhen = "onActiveAlert"
summary = true
[rule.actions.params]
body = """
{ "text": "\r\nAlert: {{rule.name}}\r\nMessage: {{context.message}}\r\nRule URL:
https://ccs-centralize.kb.ap-southeast-1.aws.found.io:9243/{{rule.url}}\r\nRule Description:
{{context.rule.description}}\r\n\r\n " }
"""
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1071"
name = "Application Layer Protocol"
reference = "https://attack.mitre.org/techniques/T1071/"
[[rule.threat.technique.subtechnique]]
id = "T1071.001"
name = "Web Protocols"
reference = "https://attack.mitre.org/techniques/T1071/001/"



[rule.threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[rule.meta]
from = "30m"
kibana_siem_app_url = "https://tiamut-uat.kb.ap-southeast-1.aws.found.io/app/security"

