[metadata]
creation_date = "2024/11/18"
maturity = "production"
updated_date = "2024/11/18"

[rule]
anomaly_threshold = 50
author = ["Elastic"]
description = """
A machine learning job detected unusually large numbers of DNS queries for a single top-level DNS domain, which is often
used for DNS tunneling. DNS tunneling can be used for command-and-control, persistence, or data exfiltration activity.
For example, dnscat tends to generate many DNS questions for a top-level domain as it uses the DNS protocol to tunnel
data.
"""
enabled = true
exceptions_list = []
false_positives = [
    """
    DNS domains that use large numbers of child domains, such as software or content distribution networks, can trigger
    this alert and such parent domains can be excluded.
    """,
]
from = "now-2700s"
interval = "15m"
license = "Elastic License v2"
machine_learning_job_id = ["orange-v1-packetbeat_dns_tunneling"]
max_signals = 100
name = "Orange-ML102 DNS Tunneling"
references = ["https://www.elastic.co/guide/en/security/current/prebuilt-ml-jobs.html"]
related_integrations = []
required_fields = []
revision = 0
risk_score = 21
risk_score_mapping = []
rule_id = "dab13bc2-d240-4083-b701-2049c27ad396"
setup = ""
severity = "low"
severity_mapping = []
tags = ["Elastic", "Network", "Threat Detection", "ML", "Machine Learning", "Command and Control"]
to = "now"
type = "machine_learning"
version = 102
[[rule.actions]]
action_type_id = ".webhook"
group = "default"
id = "a9df16c0-0f0f-11ee-a14f-a505e9bdd204"
uuid = "e3057728-2c0c-41e5-9fa4-4dd2c6821f04"

[rule.actions.frequency]
notifyWhen = "onActiveAlert"
summary = true
[rule.actions.params]
body = """
{ "text": "\r\nAlert: {{rule.name}}\r\nMessage: {{context.message}}\r\nRule URL:
https://ccs-centralize.kb.ap-southeast-1.aws.found.io:9243/{{rule.url}}\r\nRule Description:
{{context.rule.description}}\r\n\r\n " }
"""
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1572"
name = "Protocol Tunneling"
reference = "https://attack.mitre.org/techniques/T1572/"
subtechnique = []


[rule.threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[rule.meta]
from = "30m"
kibana_siem_app_url = "https://tiamut-uat.kb.ap-southeast-1.aws.found.io/app/security"

