[metadata]
creation_date = "2024/11/19"
maturity = "production"
updated_date = "2024/11/19"

[rule]
anomaly_threshold = 50
author = ["Elastic"]
description = """
A machine learning job detected a rare and unusual URL that indicates unusual web browsing activity. This can be due to
initial access, persistence, command-and-control, or exfiltration activity. For example, in a strategic web compromise
or watering hole attack, when a trusted website is compromised to target a particular sector or organization, targeted
users may receive emails with uncommon URLs for trusted websites. These URLs can be used to download and run a payload.
When malware is already running, it may send requests to uncommon URLs on trusted websites the malware uses for
command-and-control communication. When rare URLs are observed being requested for a local web server by a remote
source, these can be due to web scanning, enumeration or attack traffic, or they can be due to bots and web scrapers
which are part of common Internet background traffic.
"""
enabled = true
exceptions_list = []
false_positives = [
    """
    Web activity that occurs rarely in small quantities can trigger this alert. Possible examples are browsing technical
    support or vendor URLs that are used very sparsely. A user who visits a new and unique web destination may trigger
    this alert when the activity is sparse. Web applications that generate URLs unique to a transaction may trigger this
    when they are used sparsely. Web domains can be excluded in cases such as these.
    """,
]
from = "now-2700s"
interval = "15m"
license = "Elastic License v2"
machine_learning_job_id = ["orange-v1-packetbeat_rare_urls"]
max_signals = 100
name = "Orange-ML306 Unusual Web Request"
references = ["https://www.elastic.co/guide/en/security/current/prebuilt-ml-jobs.html"]
related_integrations = []
required_fields = []
revision = 0
risk_score = 21
risk_score_mapping = []
rule_id = "8c129083-b618-48d3-b959-24e1071e2421"
setup = ""
severity = "low"
severity_mapping = []
tags = ["Elastic", "Network", "Threat Detection", "ML", "Machine Learning", "Command and Control"]
to = "now"
type = "machine_learning"
version = 103
[[rule.actions]]
action_type_id = ".webhook"
group = "default"
id = "a9df16c0-0f0f-11ee-a14f-a505e9bdd204"
uuid = "38796125-4bae-49c1-8c65-6eb6df5cf24d"

[rule.actions.frequency]
notifyWhen = "onActiveAlert"
summary = true
[rule.actions.params]
body = """
{ "text": "\r\nAlert: {{rule.name}}\r\nMessage: {{context.message}}\r\nRule URL:
https://ccs-centralize.kb.ap-southeast-1.aws.found.io:9243/{{rule.url}}\r\nRule Description:
{{context.rule.description}}\r\n\r\n " }
"""
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1071"
name = "Application Layer Protocol"
reference = "https://attack.mitre.org/techniques/T1071/"
[[rule.threat.technique.subtechnique]]
id = "T1071.001"
name = "Web Protocols"
reference = "https://attack.mitre.org/techniques/T1071/001/"



[rule.threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[rule.meta]
from = "30m"
kibana_siem_app_url = ""

