[metadata]
creation_date = "2024/11/11"
maturity = "production"
updated_date = "2024/11/11"

[rule]
anomaly_threshold = 50
author = ["Elastic"]
description = """
A machine learning job detected a rare and unusual DNS query that indicate network activity with unusual DNS domains.
This can be due to initial access, persistence, command-and-control, or exfiltration activity. For example, when a user
clicks on a link in a phishing email or opens a malicious document, a request may be sent to download and run a payload
from an uncommon domain. When malware is already running, it may send requests to an uncommon DNS domain the malware
uses for command-and-control communication.
"""
enabled = true
exceptions_list = []
false_positives = [
    """
    A newly installed program or one that runs rarely as part of a monthly or quarterly workflow could trigger this
    alert. Network activity that occurs rarely, in small quantities, can trigger this alert. Possible examples are
    browsing technical support or vendor networks sparsely. A user who visits a new or unique web destination may
    trigger this alert.
    """,
]
from = "now-2700s"
interval = "15m"
license = "Elastic License v2"
machine_learning_job_id = ["orange-v1-packetbeat_rare_dns_question"]
max_signals = 100
name = "Orange-ML304 Unusual DNS Activity"
references = ["https://www.elastic.co/guide/en/security/current/prebuilt-ml-jobs.html"]
related_integrations = []
required_fields = []
revision = 0
risk_score = 21
risk_score_mapping = []
rule_id = "2a9f7836-45d4-423a-be84-4c4879251007"
setup = ""
severity = "low"
severity_mapping = []
tags = ["Elastic", "Network", "Threat Detection", "ML", "Machine Learning", "Command and Control"]
to = "now"
type = "machine_learning"
version = 102
[[rule.actions]]
action_type_id = ".webhook"
group = "default"
id = "a9df16c0-0f0f-11ee-a14f-a505e9bdd204"
uuid = "61b955d8-2a6b-443e-8904-5beb86b17a14"

[rule.actions.frequency]
notifyWhen = "onActiveAlert"
summary = true
[rule.actions.params]
body = '{ "text" : "{{rule.name}} {{context.rule.description}}{{context.alerts}} " }
'
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1071"
name = "Application Layer Protocol"
reference = "https://attack.mitre.org/techniques/T1071/"
[[rule.threat.technique.subtechnique]]
id = "T1071.004"
name = "DNS"
reference = "https://attack.mitre.org/techniques/T1071/004/"



[rule.threat.tactic]
id = "TA0011"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0011/"

[rule.meta]
from = "30m"
kibana_siem_app_url = ""

