[metadata]
creation_date = "2024/10/03"
maturity = "production"
updated_date = "2024/10/03"

[rule]
actions = []
author = ["Elastic"]
description = """
Detects attempts to install or use Kali Linux via Windows Subsystem for Linux. Adversaries may enable and use WSL for
Linux to avoid detection.
"""
enabled = false
exceptions_list = []
false_positives = []
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*", "logs-windows.*", "endgame-*"]
interval = "5m"
language = "eql"
license = "Elastic License v2"
max_signals = 100
name = "Attempt to Install Kali Linux via WSL [Duplicate]"
references = ["https://learn.microsoft.com/en-us/windows/wsl/wsl-config"]
related_integrations = []
required_fields = []
revision = 0
risk_score = 73
risk_score_mapping = []
rule_id = "66d88140-846b-4d9a-af85-8bb7323c0690"
setup = ""
severity = "high"
severity_mapping = []
tags = [
    "Domain: Endpoint",
    "OS: Windows",
    "Use Case: Threat Detection",
    "Tactic: Defense Evasion",
    "Data Source: Elastic Endgame",
    "Data Source: Elastic Defend",
]
timestamp_override = "event.ingested"
to = "now"
type = "eql"
version = 5

query = '''
process where host.os.type == "windows" and event.type == "start" and
(
 (process.name : "wsl.exe" and process.args : ("-d", "--distribution", "-i", "--install") and process.args : "kali*") or 
 process.executable : 
        ("?:\\Users\\*\\AppData\\Local\\packages\\kalilinux*", 
         "?:\\Users\\*\\AppData\\Local\\Microsoft\\WindowsApps\\kali.exe",
         "?:\\Program Files*\\WindowsApps\\KaliLinux.*\\kali.exe")
 )
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1202"
name = "Indirect Command Execution"
reference = "https://attack.mitre.org/techniques/T1202/"


[rule.threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

