[metadata]
creation_date = "2024/10/04"
maturity = "production"
updated_date = "2024/10/04"

[rule]
actions = []
anomaly_threshold = 75
author = []
description = "ml"
enabled = true
exceptions_list = []
false_positives = []
from = "now-360s"
interval = "5m"
license = ""
machine_learning_job_id = ["auth_rare_hour_for_a_user"]
max_signals = 100
name = "ml-job"
references = []
related_integrations = []
required_fields = []
revision = 0
risk_score = 20
risk_score_mapping = []
rule_id = "75658ab1-2f44-41f6-9bb0-c97ee95a13e2"
setup = ""
severity = "low"
severity_mapping = []
tags = ["dat06", "ml-rule"]
threat = []
to = "now"
type = "machine_learning"
version = 1

[rule.meta]
from = "1m"
kibana_siem_app_url = "https://ccs-centralize.kb.ap-southeast-1.aws.found.io:9243/app/security"

