[metadata]
creation_date = "2024/10/03"
maturity = "production"
updated_date = "2024/10/03"

[rule]
anomaly_threshold = 75
author = ["Elastic"]
description = """
A machine learning job detected a rare destination country name in the network logs. This can be due to initial access,
persistence, command-and-control, or exfiltration activity. For example, when a user clicks on a link in a phishing
email or opens a malicious document, a request may be sent to download and run a payload from a server in a country
which does not normally appear in network traffic or business work-flows. Malware instances and persistence mechanisms
may communicate with command-and-control (C2) infrastructure in their country of origin, which may be an unusual
destination country for the source network.
"""
enabled = true
exceptions_list = []
false_positives = [
    """
    Business workflows that occur very occasionally, and involve a business relationship with an organization in a
    country that does not routinely appear in network events, can trigger this alert. A new business workflow with an
    organization in a country with which no workflows previously existed may trigger this alert - although the model
    will learn that the new destination country is no longer anomalous as the activity becomes ongoing. Business
    travelers who roam to many countries for brief periods may trigger this alert.
    """,
]
from = "now-1800s"
interval = "15m"
license = "Elastic License v2"
machine_learning_job_id = ["orange-v1-rare_destination_country"]
max_signals = 100
name = "Orange-ML101 Network Traffic to Rare Destination Country"
references = ["https://www.elastic.co/guide/en/security/current/prebuilt-ml-jobs.html"]
related_integrations = []
required_fields = []
revision = 0
risk_score = 21
risk_score_mapping = []
rule_id = "6a784a4d-8910-4eaf-b189-f4781079a0b1"
setup = ""
severity = "low"
severity_mapping = []
tags = ["Elastic", "Network", "Threat Detection", "ML", "Machine Learning"]
threat = []
to = "now"
type = "machine_learning"
version = 106
[[rule.actions]]
action_type_id = ".webhook"
group = "default"
id = "a9df16c0-0f0f-11ee-a14f-a505e9bdd204"
uuid = "ac565547-4ec3-4c35-a326-7bf351cb799f"

[rule.actions.frequency]
notifyWhen = "onActiveAlert"
summary = true
[rule.actions.params]
body = """
{ "text": "\r\nAlert: {{rule.name}}\r\nMessage: {{context.message}}\r\nRule URL:
https://ccs-centralize.kb.ap-southeast-1.aws.found.io:9243/{{rule.url}}\r\nRule Description:
{{context.rule.description}}\r\n\r\n " }
"""

[rule.meta]
from = "15m"
kibana_siem_app_url = ""

