[metadata]
creation_date = "2024/11/13"
maturity = "production"
updated_date = "2024/11/13"

[rule]
author = ["Palo"]
data_view_id = "478e5fee-227d-4979-a627-132a4e24af8d"
description = "Orange-FXT-ES-ETIMEDOUT-ERROR more than 10 times per minute"
enabled = false
exceptions_list = []
false_positives = []
filters = []
from = "now-120s"
interval = "1m"
language = "kuery"
license = ""
max_signals = 100
name = "Orange-FXT-ES-ETIMEDOUT-ERROR"
references = []
related_integrations = []
required_fields = []
revision = 0
risk_score = 99
risk_score_mapping = []
rule_id = "ab6ce38b-b5dd-4adc-9b9e-f4347cba7606"
setup = ""
severity = "critical"
severity_mapping = []
tags = ["Orange", "Custom", "Foxtort"]
threat = []
to = "now"
type = "query"
version = 1

query = '''
message: ETIMEDOUT
'''


[[rule.actions]]
action_type_id = ".email"
group = "default"
id = "elastic-cloud-email"
uuid = "9265d420-9500-4c52-9bdd-08c0d67d8c3a"

[rule.actions.frequency]
notifyWhen = "onActiveAlert"
summary = true
[rule.actions.params]
message = "Rule {{context.rule.name}} generated {{state.signals_count}} alerts"
subject = "Orange-FXT-ES-ETIMEDOUT-ERROR"
to = ["palo.aug@orangeworking.com"]
[[rule.actions]]
action_type_id = ".webhook"
group = "default"
id = "73d17ba0-d5a6-11ee-96b3-8906b70ceadc"
uuid = "2e1f0bea-dc33-41b3-b560-d787a97c1270"

[rule.actions.frequency]
notifyWhen = "onActiveAlert"
summary = true
[rule.actions.params]
body = """
{ "text": "\r\nRule Name : {{rule.name}}\r\nSeverity: {{context.rule.severity}}\r\nAlert: {{rule.name}}\r\nMessage:
{{context.message}}\r\nRule URL: {{rule.url}}\r\nRule Description: {{context.rule.description}}\r\nAlert Count :
{{alerts.all.count}}\r\nAlert Data : {{alerts.all.data}}\r\n\r\n " }
"""

[rule.investigation_fields]
field_names = ["message", "kubernetes.container.name"]

[rule.meta]
from = "1m"
kibana_siem_app_url = "https://ccs-centralize.kb.ap-southeast-1.aws.found.io:9243/app/security"

