[metadata]
creation_date = "2024/11/13"
maturity = "production"
updated_date = "2024/11/13"

[rule]
anomaly_threshold = 50
author = ["Elastic"]
description = """
A machine learning job detected an unusual network destination domain name. This can be due to initial access,
persistence, command-and-control, or exfiltration activity. For example, when a user clicks on a link in a phishing
email or opens a malicious document, a request may be sent to download and run a payload from an uncommon web server
name. When malware is already running, it may send requests to an uncommon DNS domain the malware uses for
command-and-control communication.
"""
enabled = true
exceptions_list = []
false_positives = [
    """
    Web activity that occurs rarely in small quantities can trigger this alert. Possible examples are browsing technical
    support or vendor URLs that are used very sparsely. A user who visits a new and unique web destination may trigger
    this alert when the activity is sparse. Web applications that generate URLs unique to a transaction may trigger this
    when they are used sparsely. Web domains can be excluded in cases such as these.
    """,
]
from = "now-2700s"
interval = "15m"
license = "Elastic License v2"
machine_learning_job_id = ["orange-v1-packetbeat_rare_server_domain"]
max_signals = 100
name = "Orange-ML305 Unusual Network Destination Domain Name"
references = ["https://www.elastic.co/guide/en/security/current/prebuilt-ml-jobs.html"]
related_integrations = []
required_fields = []
revision = 0
risk_score = 21
risk_score_mapping = []
rule_id = "44c2cc98-59af-4011-aaee-d4416c4afbef"
setup = ""
severity = "low"
severity_mapping = []
tags = ["Elastic", "Network", "Threat Detection", "ML", "Machine Learning"]
threat = []
to = "now"
type = "machine_learning"
version = 103
[[rule.actions]]
action_type_id = ".webhook"
group = "default"
id = "a9df16c0-0f0f-11ee-a14f-a505e9bdd204"
uuid = "62c24d93-1bbd-4c70-89b8-d16cd966529f"

[rule.actions.frequency]
notifyWhen = "onActiveAlert"
summary = true
[rule.actions.params]
body = """
{ "text": "\r\nAlert: {{rule.name}}\r\nMessage: {{context.message}}\r\nRule URL:
https://ccs-centralize.kb.ap-southeast-1.aws.found.io:9243/{{rule.url}}\r\nRule Description:
{{context.rule.description}}\r\n\r\n " }
"""

[rule.meta]
from = "30m"
kibana_siem_app_url = ""

