[metadata]
creation_date = "2024/11/11"
maturity = "production"
updated_date = "2024/11/11"

[rule]
actions = []
anomaly_threshold = 50
author = ["Elastic"]
description = """
Looks for compiler activity by a user context which does not normally run compilers. This can be the result of ad-hoc
software changes or unauthorized software deployment. This can also be due to local privilege elevation via locally run
exploits or malware activity.
"""
enabled = false
exceptions_list = []
false_positives = [
    """
    Uncommon compiler activity can be due to an engineer running a local build on a production or staging instance in
    the course of troubleshooting or fixing a software issue.
    """,
]
from = "now-45m"
interval = "15m"
license = "Elastic License v2"
machine_learning_job_id = ["v3_linux_rare_user_compiler"]
max_signals = 100
name = "Anomalous Linux Compiler Activity [Duplicate]"
references = []
related_integrations = []
required_fields = []
revision = 0
risk_score = 21
risk_score_mapping = []
rule_id = "1dca7902-bf77-4ce6-8005-cdccf55925c3"
setup = ""
severity = "low"
severity_mapping = []
tags = [
    "Domain: Endpoint",
    "OS: Linux",
    "Use Case: Threat Detection",
    "Rule Type: ML",
    "Rule Type: Machine Learning",
    "Tactic: Resource Development",
]
to = "now"
type = "machine_learning"
version = 103
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1588"
name = "Obtain Capabilities"
reference = "https://attack.mitre.org/techniques/T1588/"
[[rule.threat.technique.subtechnique]]
id = "T1588.001"
name = "Malware"
reference = "https://attack.mitre.org/techniques/T1588/001/"



[rule.threat.tactic]
id = "TA0042"
name = "Resource Development"
reference = "https://attack.mitre.org/tactics/TA0042/"

