# For more details, refer to the example configuration:
# C:\Users\Administrator\Desktop\zsoham-detection-rules\detection_rules\etc\example_test_config.yaml
# Define tests to explicitly bypass, with all others being run.
# To run all tests, set bypass to empty or leave this file commented out.

unit_tests:
  bypass:
  - tests.test_gh_workflows.TestWorkflows.test_matrix_to_lock_version_defaults
  - tests.test_schemas.TestVersionLockSchema.test_version_lock_has_nested_previous
  - tests.test_packages.TestRegistryPackage.test_registry_package_config
  - tests.test_all_rules.TestValidRules.test_schema_and_dupes
  - tests.test_all_rules.TestRuleMetadata.test_invalid_queries
  - tests.test_all_rules.TestValidRules.test_bbr_validation
  - tests.test_all_rules.TestValidRules.test_rule_type_changes
  - tests.test_schemas.TestSchemas.test_eql_validation