name: Manually Sync Rules from Elastic Security to GitHub

on:
  pull_request:
    branches: ["dev-palo"]
  workflow_dispatch:
    inputs:
      pr_sync_rules_from_elastic:
        description: 'Sync rules from Elastic Security (direct commit (false) vs PR (true))'
        required: true
        default: 'true'
      space:
        description: 'Specify the Kibana space to export rules from'
        required: false
        default: 'Default'

jobs:
  manual-dispatch-sync:
    runs-on: ["self-hosted", "windows"]
    env:
      CUSTOM_RULES_DIR: nonprod_export_rules
      PYTHONUTF8: '1'

    steps:
      - name: Retrieve Secrets
        uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        id: secrets
        with:
          url: "${{ secrets.RAINBOW_VAULT_ADDR }}"
          method: "jwt"
          path: "jwt-github"
          role: "github-actions-role"
          namespace: admin
          secrets: |
            secrets/global/elastic-cloud/tyson-tech/dev/nonprod-playground/services-accounts/dac/CLOUD_ID | CLOUD_ID;
            secrets/global/elastic-cloud/tyson-tech/dev/nonprod-playground/services-accounts/dac/KIBANA_USERNAME | KIBANA_USERNAME;
            secrets/global/elastic-cloud/tyson-tech/dev/nonprod-playground/services-accounts/dac/KIBANA_PASSWORD | KIBANA_PASSWORD;

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip cache purge
          pip install .[dev]
        shell: cmd

      - name: Debug Environment Variables
        run: |
          echo CUSTOM_RULES_DIR: %CUSTOM_RULES_DIR%
          echo DR_CLOUD_ID: %CLOUD_ID%
          echo DR_KIBANA_USER: %KIBANA_USERNAME%
          echo DR_KIBANA_PASSWORD: %KIBANA_PASSWORD%
        shell: cmd

      - name: Export Rules from Elastic Security and Import Rules to TOML
        if: ${{ github.event.inputs.pr_sync_rules_from_elastic == 'true' }}
        run: |
          python -m detection_rules kibana export-rules --directory %CUSTOM_RULES_DIR% --skip-errors
        env:
          DR_CLOUD_ID: ${{ secrets.CLOUD_ID }}
          DR_KIBANA_USER: ${{ secrets.KIBANA_USERNAME }}
          DR_KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD }}
        shell: cmd

      - name: Update Version Lock
        run: |
          python -m detection_rules dev update-lock-versions --force
        shell: cmd
