name: Push Latest Rules to Elastic Security Space

on:
  push:
    branches:
      - main
    paths:
      - '/*.toml'
  workflow_dispatch:
    inputs:
      overwrite:
        description: 'Overwrite existing rules'
        required: false
        default: 'true'
      overwrite_exceptions:
        description: 'Overwrite existing exceptions'
        required: false
        default: 'true'
      overwrite_action_connectors:
        description: 'Overwrite existing action connectors'
        required: false
        default: 'true'
      space:
        description: 'Kibana space to use (prod or non-prod)'
        required: false
        default: 'Default'

jobs:
  sync-to-production:
    runs-on: self-hosted
    env:
      CUSTOM_RULES_DIR: ${{ secrets.CUSTOM_RULES_DIR }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies in Virtual Environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Import Rules to Kibana
      run: |
        source venv/bin/activate
        FLAGS=""
        if [ "$GITHUB_EVENT_NAME" = "push" ] && [ "$INPUT_OVERWRITE" = "true" ]; then
          FLAGS+=" --overwrite"
        fi
        if [ "$GITHUB_EVENT_NAME" = "push" ] && [ "$INPUT_OVERWRITE_EXCEPTIONS" = "true" ]; then
          FLAGS+=" --overwrite-exceptions"
        fi
        if [ "$GITHUB_EVENT_NAME" = "push" ] && [ "$INPUT_OVERWRITE_ACTION_CONNECTORS" = "true" ]; then
          FLAGS+=" --overwrite-action-connectors"
        fi
        SPACE="${INPUT_SPACE:-Default}"
        SPACE_FLAG="--space $SPACE"
        echo "Running command: python3 -m detection_rules kibana $SPACE_FLAG import-rules $FLAGS"
        python3 -m detection_rules kibana $SPACE_FLAG import-rules $FLAGS
      env:
        DR_CLOUD_ID: ${{ secrets.CLOUD_ID }}
        DR_KIBANA_USER: ${{ secrets.KIBANA_USERNAME }}
        DR_KIBANA_PASSWORD: ${{ secrets.KIBANA_PASSWORD }}
